In [1]:
import pandas as pd
from zipfile import ZipFile

In [2]:
pd.set_option('display.max_columns', None) 
pd.set_option('display.max_rows', None)

In [3]:
zf = ZipFile("../../Data/sim_sact_patient.zip")
csv = zf.open("sim_sact_patient.csv")
sim_sact_patient = pd.read_csv(csv)
sim_sact_patient.head()

   MERGED_PATIENT_ID  LINK_NUMBER
0           10000087    810000087
1           10000235    810000235
2           10000283    810000283
3           10000315    810000315
4           10000337    810000337

In [4]:
sim_sact_patient.shape

(245938, 2)

In [5]:
sim_sact_patient.isna().sum()

MERGED_PATIENT_ID    0
LINK_NUMBER          0
dtype: int64

In [6]:
sim_sact_patient['LINK_NUMBER'].nunique()

245938

In [7]:
print("The original dataset has data for %d patients" % len(sim_sact_patient))
print("After removing duplicates, the dataset has data for %d patients" % len(sim_sact_patient.drop_duplicates()))
print("There are no duplicates in the dataset")

The original dataset has data for 245938 patients
After removing duplicates, the dataset has data for 245938 patients
There are no duplicates in the dataset

In [8]:
sim_sact_patient[sim_sact_patient.groupby('MERGED_PATIENT_ID')['MERGED_PATIENT_ID'].transform('size') > 1].count()

MERGED_PATIENT_ID    0
LINK_NUMBER          0
dtype: int64

In [9]:
df = pd.read_csv("./Data/avpat_avtum.csv", sep = '^', index_col = 0)
df.head()

,PATIENTID,SEX,LINKNUMBER,ETHNICITY,NEWVITALSTATUS,NUMBER_TUMOURS,SC500,SC501,SC502,SC503,SC504,SC505,SC506,SC508,BEH_BENIGN,BEH_MALIG,BEH_MICINV,BEH_INSITU,BEH_UNCERT,T0,T1,T2,T3,T4,N0,N1,N2,N3,M1,STAGE0,STAGE1,STAGE2,STAGE3,STAGE4,GRADE1,GRADE2,GRADE3,GRADE4,AGE_MEAN,L0801,L1001,L1701,L0201,L0401,L1201,L0301,L0901,ER_POS,PR_POS,HER_POS,CURATIVE,NONCURATIVE,NOACTTREAT,ECOG0,ECOG1,ECOG2,ECOG3,ECOG4,ACE0,ACE1,ACE2,ACE3,LEFT,RIGHT,MIDLINE,BILATERAL,DEPR1,DEPR2,DEPR3,DEPR4,DEPR5,CANCER_DAYS_MEAN,CANCER_MONTHS_MEAN,CANCER_YEARS_MEAN
624,10000724,M,810000724,White British,A,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False,False,True,False,False,71.0,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,1226.0,40.280088,3.356674
650,10000752,F,810000752,White British,A,1,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,68.0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,432.0,14.193310,1.182776
913,10001050,F,810001050,White British,A,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,False,True,False,86.0,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,450.0,14.784698,1.232058
1543,10001750,M,810001750,White British,A,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,71.0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,846.0,27.795232,2.316269
1613,10001824,F,810001824,Other ethnic group,A,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,87.0,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,674.0,22.144192,1.845349

In [10]:
df.shape

(105686, 74)

In [11]:
df = df.merge(sim_sact_patient, left_on = 'LINKNUMBER', right_on = 'LINK_NUMBER', how = 'left')
df.head()

,PATIENTID,SEX,LINKNUMBER,ETHNICITY,NEWVITALSTATUS,NUMBER_TUMOURS,SC500,SC501,SC502,SC503,SC504,SC505,SC506,SC508,BEH_BENIGN,BEH_MALIG,BEH_MICINV,BEH_INSITU,BEH_UNCERT,T0,T1,T2,T3,T4,N0,N1,N2,N3,M1,STAGE0,STAGE1,STAGE2,STAGE3,STAGE4,GRADE1,GRADE2,GRADE3,GRADE4,AGE_MEAN,L0801,L1001,L1701,L0201,L0401,L1201,L0301,L0901,ER_POS,PR_POS,HER_POS,CURATIVE,NONCURATIVE,NOACTTREAT,ECOG0,ECOG1,ECOG2,ECOG3,ECOG4,ACE0,ACE1,ACE2,ACE3,LEFT,RIGHT,MIDLINE,BILATERAL,DEPR1,DEPR2,DEPR3,DEPR4,DEPR5,CANCER_DAYS_MEAN,CANCER_MONTHS_MEAN,CANCER_YEARS_MEAN,MERGED_PATIENT_ID,LINK_NUMBER
0,10000724,M,810000724,White British,A,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False,False,True,False,False,71.0,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,1226.0,40.280088,3.356674,NaN,NaN
1,10000752,F,810000752,White British,A,1,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,68.0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,432.0,14.193310,1.182776,NaN,NaN
2,10001050,F,810001050,White British,A,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,False,True,False,86.0,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,450.0,14.784698,1.232058,NaN,NaN
3,10001750,M,810001750,White British,A,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,71.0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,846.0,27.795232,2.316269,NaN,NaN
4,10001824,F,810001824,Other ethnic group,A,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,87.0,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,674.0,22.144192,1.845349,NaN,NaN

In [12]:
df.shape

(105686, 76)

In [13]:
df[df.groupby('PATIENTID')['PATIENTID'].transform('size') > 1].count()

PATIENTID             0
SEX                   0
LINKNUMBER            0
ETHNICITY             0
NEWVITALSTATUS        0
NUMBER_TUMOURS        0
SC500                 0
SC501                 0
SC502                 0
SC503                 0
SC504                 0
SC505                 0
SC506                 0
SC508                 0
BEH_BENIGN            0
BEH_MALIG             0
BEH_MICINV            0
BEH_INSITU            0
BEH_UNCERT            0
T0                    0
T1                    0
T2                    0
T3                    0
T4                    0
N0                    0
N1                    0
N2                    0
N3                    0
M1                    0
STAGE0                0
STAGE1                0
STAGE2                0
STAGE3                0
STAGE4                0
GRADE1                0
GRADE2                0
GRADE3                0
GRADE4                0
AGE_MEAN              0
L0801                 0
L1001                 0
L1701                 0
L0201                 0
L0401                 0
L1201                 0
L0301                 0
L0901                 0
ER_POS                0
PR_POS                0
HER_POS               0
CURATIVE              0
NONCURATIVE           0
NOACTTREAT            0
ECOG0                 0
ECOG1                 0
ECOG2                 0
ECOG3                 0
ECOG4                 0
ACE0                  0
ACE1                  0
ACE2                  0
ACE3                  0
LEFT                  0
RIGHT                 0
MIDLINE               0
BILATERAL             0
DEPR1                 0
DEPR2                 0
DEPR3                 0
DEPR4                 0
DEPR5                 0
CANCER_DAYS_MEAN      0
CANCER_MONTHS_MEAN    0
CANCER_YEARS_MEAN     0
MERGED_PATIENT_ID     0
LINK_NUMBER           0
dtype: int64

In [14]:
df.isna().sum()

PATIENTID                 0
SEX                       0
LINKNUMBER                0
ETHNICITY              6918
NEWVITALSTATUS            0
NUMBER_TUMOURS            0
SC500                     0
SC501                     0
SC502                     0
SC503                     0
SC504                     0
SC505                     0
SC506                     0
SC508                     0
BEH_BENIGN                0
BEH_MALIG                 0
BEH_MICINV                0
BEH_INSITU                0
BEH_UNCERT                0
T0                        0
T1                        0
T2                        0
T3                        0
T4                        0
N0                        0
N1                        0
N2                        0
N3                        0
M1                        0
STAGE0                    0
STAGE1                    0
STAGE2                    0
STAGE3                    0
STAGE4                    0
GRADE1                    0
GRADE2                    0
GRADE3                    0
GRADE4                    0
AGE_MEAN                  0
L0801                     0
L1001                     0
L1701                     0
L0201                     0
L0401                     0
L1201                     0
L0301                     0
L0901                     0
ER_POS                    0
PR_POS                    0
HER_POS                   0
CURATIVE                  0
NONCURATIVE               0
NOACTTREAT                0
ECOG0                     0
ECOG1                     0
ECOG2                     0
ECOG3                     0
ECOG4                     0
ACE0                      0
ACE1                      0
ACE2                      0
ACE3                      0
LEFT                      0
RIGHT                     0
MIDLINE                   0
BILATERAL                 0
DEPR1                     0
DEPR2                     0
DEPR3                     0
DEPR4                     0
DEPR5                     0
CANCER_DAYS_MEAN          0
CANCER_MONTHS_MEAN        0
CANCER_YEARS_MEAN         0
MERGED_PATIENT_ID     65605
LINK_NUMBER           65605
dtype: int64

In [15]:
df.to_csv('./Data/avpat_avtum_sactpat.csv', sep='^')