In [1]:
import pandas as pd
import numpy as np
from zipfile import ZipFile

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
zf = ZipFile("../../Data/sim_sact_tumour.zip")
csv = zf.open("sim_sact_tumour.csv")
sim_sact_tumour = pd.read_csv(csv)
sim_sact_tumour.head()

,MERGED_TUMOUR_ID,MERGED_PATIENT_ID,CONSULTANT_SPECIALITY_CODE,PRIMARY_DIAGNOSIS,MORPHOLOGY_CLEAN
0,10000001,10000235,101.0,C61,81403.0
1,10000002,10000315,101.0,C679,81403.0
2,10000003,10000337,100.0,C500,NaN
3,10000004,10000480,303.0,C829,NaN
4,10000005,10000533,823.0,D473,NaN

In [4]:
sim_sact_tumour.shape

(299727, 5)

In [5]:
print("The original dataset has data for %d patients" % len(sim_sact_tumour))
print("After removing duplicates, the dataset has data for %d patients" % len(sim_sact_tumour.drop_duplicates()))
print("There are no duplicates in the dataset")

The original dataset has data for 299727 patients
After removing duplicates, the dataset has data for 299727 patients
There are no duplicates in the dataset

In [6]:
sim_sact_tumour[sim_sact_tumour.groupby('MERGED_PATIENT_ID')['MERGED_PATIENT_ID'].transform('size') > 1].count()

MERGED_TUMOUR_ID              175510
MERGED_PATIENT_ID             175510
CONSULTANT_SPECIALITY_CODE    175506
PRIMARY_DIAGNOSIS             175446
MORPHOLOGY_CLEAN               86818
dtype: int64

In [7]:
sim_sact_tumour[sim_sact_tumour.groupby('MERGED_PATIENT_ID')['MERGED_PATIENT_ID'].transform('size') == 1].count()

MERGED_TUMOUR_ID              124217
MERGED_PATIENT_ID             124217
CONSULTANT_SPECIALITY_CODE    124217
PRIMARY_DIAGNOSIS             124173
MORPHOLOGY_CLEAN               67420
dtype: int64

In [8]:
sim_sact_tumour.columns

Index(['MERGED_TUMOUR_ID', 'MERGED_PATIENT_ID', 'CONSULTANT_SPECIALITY_CODE',
       'PRIMARY_DIAGNOSIS', 'MORPHOLOGY_CLEAN'],
      dtype='object')

In [9]:
columns_selected = ['MERGED_TUMOUR_ID', 'MERGED_PATIENT_ID']
sim_sact_tumour = sim_sact_tumour[columns_selected]
sim_sact_tumour.head()

   MERGED_TUMOUR_ID  MERGED_PATIENT_ID
0          10000001           10000235
1          10000002           10000315
2          10000003           10000337
3          10000004           10000480
4          10000005           10000533

In [10]:
print("The original dataset has data for %d patients" % len(sim_sact_tumour))
print("After removing duplicates, the dataset has data for %d patients" % len(sim_sact_tumour.drop_duplicates()))
print("There are no duplicates in the dataset")

The original dataset has data for 299727 patients
After removing duplicates, the dataset has data for 299727 patients
There are no duplicates in the dataset

In [11]:
df = pd.read_csv("./Data/avpat_avtum_sactpat.csv", sep = '^', index_col = 0)
df.head()

,PATIENTID,SEX,LINKNUMBER,ETHNICITY,NEWVITALSTATUS,NUMBER_TUMOURS,SC500,SC501,SC502,SC503,SC504,SC505,SC506,SC508,BEH_BENIGN,BEH_MALIG,BEH_MICINV,BEH_INSITU,BEH_UNCERT,T0,T1,T2,T3,T4,N0,N1,N2,N3,M1,STAGE0,STAGE1,STAGE2,STAGE3,STAGE4,GRADE1,GRADE2,GRADE3,GRADE4,AGE_MEAN,L0801,L1001,L1701,L0201,L0401,L1201,L0301,L0901,ER_POS,PR_POS,HER_POS,CURATIVE,NONCURATIVE,NOACTTREAT,ECOG0,ECOG1,ECOG2,ECOG3,ECOG4,ACE0,ACE1,ACE2,ACE3,LEFT,RIGHT,MIDLINE,BILATERAL,DEPR1,DEPR2,DEPR3,DEPR4,DEPR5,CANCER_DAYS_MEAN,CANCER_MONTHS_MEAN,CANCER_YEARS_MEAN,MERGED_PATIENT_ID,LINK_NUMBER
0,10000724,M,810000724,White British,A,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False,False,True,False,False,71.0,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,1226.0,40.280088,3.356674,NaN,NaN
1,10000752,F,810000752,White British,A,1,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,68.0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,432.0,14.193310,1.182776,NaN,NaN
2,10001050,F,810001050,White British,A,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,False,True,False,86.0,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,450.0,14.784698,1.232058,NaN,NaN
3,10001750,M,810001750,White British,A,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,71.0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,846.0,27.795232,2.316269,NaN,NaN
4,10001824,F,810001824,Other ethnic group,A,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,87.0,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,674.0,22.144192,1.845349,NaN,NaN

In [12]:
df.shape

(105686, 76)

In [13]:
df = df.merge(sim_sact_tumour, left_on = 'MERGED_PATIENT_ID', right_on = 'MERGED_PATIENT_ID', how = 'left')
df.head()

,PATIENTID,SEX,LINKNUMBER,ETHNICITY,NEWVITALSTATUS,NUMBER_TUMOURS,SC500,SC501,SC502,SC503,SC504,SC505,SC506,SC508,BEH_BENIGN,BEH_MALIG,BEH_MICINV,BEH_INSITU,BEH_UNCERT,T0,T1,T2,T3,T4,N0,N1,N2,N3,M1,STAGE0,STAGE1,STAGE2,STAGE3,STAGE4,GRADE1,GRADE2,GRADE3,GRADE4,AGE_MEAN,L0801,L1001,L1701,L0201,L0401,L1201,L0301,L0901,ER_POS,PR_POS,HER_POS,CURATIVE,NONCURATIVE,NOACTTREAT,ECOG0,ECOG1,ECOG2,ECOG3,ECOG4,ACE0,ACE1,ACE2,ACE3,LEFT,RIGHT,MIDLINE,BILATERAL,DEPR1,DEPR2,DEPR3,DEPR4,DEPR5,CANCER_DAYS_MEAN,CANCER_MONTHS_MEAN,CANCER_YEARS_MEAN,MERGED_PATIENT_ID,LINK_NUMBER,MERGED_TUMOUR_ID
0,10000724,M,810000724,White British,A,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False,False,True,False,False,71.0,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,1226.0,40.280088,3.356674,NaN,NaN,NaN
1,10000752,F,810000752,White British,A,1,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,68.0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,432.0,14.193310,1.182776,NaN,NaN,NaN
2,10001050,F,810001050,White British,A,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,True,False,False,True,False,86.0,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,450.0,14.784698,1.232058,NaN,NaN,NaN
3,10001750,M,810001750,White British,A,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,71.0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,846.0,27.795232,2.316269,NaN,NaN,NaN
4,10001824,F,810001824,Other ethnic group,A,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,87.0,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,674.0,22.144192,1.845349,NaN,NaN,NaN

In [14]:
df.shape

(124739, 77)

In [15]:
df = df.drop_duplicates()
df.shape

(124739, 77)

In [16]:
df[df.groupby('PATIENTID')['PATIENTID'].transform('size') > 1].head(10)

,PATIENTID,SEX,LINKNUMBER,ETHNICITY,NEWVITALSTATUS,NUMBER_TUMOURS,SC500,SC501,SC502,SC503,SC504,SC505,SC506,SC508,BEH_BENIGN,BEH_MALIG,BEH_MICINV,BEH_INSITU,BEH_UNCERT,T0,T1,T2,T3,T4,N0,N1,N2,N3,M1,STAGE0,STAGE1,STAGE2,STAGE3,STAGE4,GRADE1,GRADE2,GRADE3,GRADE4,AGE_MEAN,L0801,L1001,L1701,L0201,L0401,L1201,L0301,L0901,ER_POS,PR_POS,HER_POS,CURATIVE,NONCURATIVE,NOACTTREAT,ECOG0,ECOG1,ECOG2,ECOG3,ECOG4,ACE0,ACE1,ACE2,ACE3,LEFT,RIGHT,MIDLINE,BILATERAL,DEPR1,DEPR2,DEPR3,DEPR4,DEPR5,CANCER_DAYS_MEAN,CANCER_MONTHS_MEAN,CANCER_YEARS_MEAN,MERGED_PATIENT_ID,LINK_NUMBER,MERGED_TUMOUR_ID
38,10019777,F,810019777,White British,A,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,73.0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,558.0,18.333025,1.527752,10019777.0,810019777.0,10006318.0
39,10019777,F,810019777,White British,A,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,73.0,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,558.0,18.333025,1.527752,10019777.0,810019777.0,10010394.0
99,10046974,F,810046974,NaN,A,1,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,71.0,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,551.0,18.103041,1.508587,10046974.0,810046974.0,10002374.0
100,10046974,F,810046974,NaN,A,1,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,71.0,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,551.0,18.103041,1.508587,10046974.0,810046974.0,10005454.0
101,10046974,F,810046974,NaN,A,1,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,71.0,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,551.0,18.103041,1.508587,10046974.0,810046974.0,10005455.0
138,10064421,F,810064421,White British,A,1,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,38.0,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,395.0,12.977679,1.081473,10064421.0,810064421.0,10003361.0
139,10064421,F,810064421,White British,A,1,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,38.0,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,395.0,12.977679,1.081473,10064421.0,810064421.0,10006327.0
140,10064421,F,810064421,White British,A,1,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,38.0,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,395.0,12.977679,1.081473,10064421.0,810064421.0,10006328.0
166,10080247,M,810080247,White British,A,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,True,False,False,False,True,False,False,75.0,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,513.0,16.854556,1.404546,10080247.0,810080247.0,10002474.0
167,10080247,M,810080247,White British,A,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,True,False,False,False,True,False,False,75.0,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,513.0,16.854556,1.404546,10080247.0,810080247.0,10008613.0

In [17]:
df.isna().sum()

PATIENTID                 0
SEX                       0
LINKNUMBER                0
ETHNICITY              8169
NEWVITALSTATUS            0
NUMBER_TUMOURS            0
SC500                     0
SC501                     0
SC502                     0
SC503                     0
SC504                     0
SC505                     0
SC506                     0
SC508                     0
BEH_BENIGN                0
BEH_MALIG                 0
BEH_MICINV                0
BEH_INSITU                0
BEH_UNCERT                0
T0                        0
T1                        0
T2                        0
T3                        0
T4                        0
N0                        0
N1                        0
N2                        0
N3                        0
M1                        0
STAGE0                    0
STAGE1                    0
STAGE2                    0
STAGE3                    0
STAGE4                    0
GRADE1                    0
GRADE2                    0
GRADE3                    0
GRADE4                    0
AGE_MEAN                  0
L0801                     0
L1001                     0
L1701                     0
L0201                     0
L0401                     0
L1201                     0
L0301                     0
L0901                     0
ER_POS                    0
PR_POS                    0
HER_POS                   0
CURATIVE                  0
NONCURATIVE               0
NOACTTREAT                0
ECOG0                     0
ECOG1                     0
ECOG2                     0
ECOG3                     0
ECOG4                     0
ACE0                      0
ACE1                      0
ACE2                      0
ACE3                      0
LEFT                      0
RIGHT                     0
MIDLINE                   0
BILATERAL                 0
DEPR1                     0
DEPR2                     0
DEPR3                     0
DEPR4                     0
DEPR5                     0
CANCER_DAYS_MEAN          0
CANCER_MONTHS_MEAN        0
CANCER_YEARS_MEAN         0
MERGED_PATIENT_ID     65605
LINK_NUMBER           65605
MERGED_TUMOUR_ID      76679
dtype: int64

In [18]:
df.count()

PATIENTID             124739
SEX                   124739
LINKNUMBER            124739
ETHNICITY             116570
NEWVITALSTATUS        124739
NUMBER_TUMOURS        124739
SC500                 124739
SC501                 124739
SC502                 124739
SC503                 124739
SC504                 124739
SC505                 124739
SC506                 124739
SC508                 124739
BEH_BENIGN            124739
BEH_MALIG             124739
BEH_MICINV            124739
BEH_INSITU            124739
BEH_UNCERT            124739
T0                    124739
T1                    124739
T2                    124739
T3                    124739
T4                    124739
N0                    124739
N1                    124739
N2                    124739
N3                    124739
M1                    124739
STAGE0                124739
STAGE1                124739
STAGE2                124739
STAGE3                124739
STAGE4                124739
GRADE1                124739
GRADE2                124739
GRADE3                124739
GRADE4                124739
AGE_MEAN              124739
L0801                 124739
L1001                 124739
L1701                 124739
L0201                 124739
L0401                 124739
L1201                 124739
L0301                 124739
L0901                 124739
ER_POS                124739
PR_POS                124739
HER_POS               124739
CURATIVE              124739
NONCURATIVE           124739
NOACTTREAT            124739
ECOG0                 124739
ECOG1                 124739
ECOG2                 124739
ECOG3                 124739
ECOG4                 124739
ACE0                  124739
ACE1                  124739
ACE2                  124739
ACE3                  124739
LEFT                  124739
RIGHT                 124739
MIDLINE               124739
BILATERAL             124739
DEPR1                 124739
DEPR2                 124739
DEPR3                 124739
DEPR4                 124739
DEPR5                 124739
CANCER_DAYS_MEAN      124739
CANCER_MONTHS_MEAN    124739
CANCER_YEARS_MEAN     124739
MERGED_PATIENT_ID      59134
LINK_NUMBER            59134
MERGED_TUMOUR_ID       48060
dtype: int64

In [19]:
df.shape

(124739, 77)

In [20]:
df.to_csv('./Data/avpat_avtum_sactpat_sacttum.csv', sep = '^')