In [1]:
import pandas as pd
from zipfile import ZipFile

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
zf = ZipFile("../../Data/sim_sact_patient.zip")
csv = zf.open("sim_sact_patient.csv")
sim_sact_patient = pd.read_csv(csv)
sim_sact_patient.head()

   MERGED_PATIENT_ID  LINK_NUMBER
0           10000087    810000087
1           10000235    810000235
2           10000283    810000283
3           10000315    810000315
4           10000337    810000337

In [4]:
sim_sact_patient.shape

(245938, 2)

In [5]:
sim_sact_patient.isna().sum()

MERGED_PATIENT_ID    0
LINK_NUMBER          0
dtype: int64

In [6]:
sim_sact_patient['LINK_NUMBER'].nunique()

245938

In [7]:
print("The original dataset has data for %d patients" % len(sim_sact_patient))
print("After removing duplicates, the dataset has data for %d patients" % len(sim_sact_patient.drop_duplicates()))
print("There are no duplicates in the dataset")

The original dataset has data for 245938 patients
After removing duplicates, the dataset has data for 245938 patients
There are no duplicates in the dataset

In [9]:
df = pd.read_csv("./Data/avpat_avtum.csv", sep='^', index_col = 0)
df.head()

,PATIENTID,SEX,LINKNUMBER,ETHNICITY,NEWVITALSTATUS,VITALSTATUSDATE,TUMOURID,DIAGNOSISDATEBEST,SITE_ICD10_O2,SITE_ICD10_O2_3CHAR,MORPH_ICD10_O2,BEHAVIOUR_ICD10_O2,T_BEST,N_BEST,M_BEST,STAGE_BEST,STAGE_BEST_SYSTEM,GRADE,AGE,CREG_CODE,ER_STATUS,ER_SCORE,SCREENINGSTATUSFULL_CODE,PR_STATUS,PR_SCORE,HER2_STATUS,CANCERCAREPLANINTENT,PERFORMANCESTATUS,CNS,ACE27,DATE_FIRST_SURGERY,LATERALITY,QUINTILE_2015
624,10000724,M,810000724,A,A,2017-01-16,10335800,2013-09-08,NaN,C50,8130.0,Malignant,2,0,0,2B,22.0,G2,71,L1201,NaN,NaN,NaN,NaN,NaN,NaN,Curative,NaN,NaN,NaN,NaN,R,3
650,10000752,F,810000752,A,A,2017-01-16,10335805,2015-11-11,C504,C50,8140.0,Malignant,NaN,0,NaN,NaN,22.0,G2,68,L0801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-09-18,L,1 - least deprived
913,10001050,F,810001050,A,A,2017-01-16,10335823,2015-10-24,NaN,C50,8130.0,Malignant,NaN,3,1,4C,22.0,G3,86,L0401,NaN,NaN,NaN,NaN,NaN,NaN,Non curative,NaN,NaN,NaN,2015-12-15,L,4
1543,10001750,M,810001750,A,A,2017-01-16,10335873,2014-09-23,NaN,C50,8070.0,Malignant,NaN,NaN,NaN,NaN,NaN,G1,71,L0801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-09-23,L,1 - least deprived
1613,10001824,F,810001824,S,A,2017-01-17,10335879,2015-03-15,NaN,C50,8070.0,Malignant,2b,NaN,0,3A,NaN,G2,87,L0801,NaN,NaN,NaN,NaN,NaN,NaN,Curative,1,NaN,NaN,2015-03-15,L,4

In [10]:
df.shape

(103192, 33)

In [11]:
df = df.merge(sim_sact_patient, left_on = 'LINKNUMBER', right_on = 'LINK_NUMBER', how = 'left')

In [12]:
df.head()

,PATIENTID,SEX,LINKNUMBER,ETHNICITY,NEWVITALSTATUS,VITALSTATUSDATE,TUMOURID,DIAGNOSISDATEBEST,SITE_ICD10_O2,SITE_ICD10_O2_3CHAR,MORPH_ICD10_O2,BEHAVIOUR_ICD10_O2,T_BEST,N_BEST,M_BEST,STAGE_BEST,STAGE_BEST_SYSTEM,GRADE,AGE,CREG_CODE,ER_STATUS,ER_SCORE,SCREENINGSTATUSFULL_CODE,PR_STATUS,PR_SCORE,HER2_STATUS,CANCERCAREPLANINTENT,PERFORMANCESTATUS,CNS,ACE27,DATE_FIRST_SURGERY,LATERALITY,QUINTILE_2015,MERGED_PATIENT_ID,LINK_NUMBER
0,10000724,M,810000724,A,A,2017-01-16,10335800,2013-09-08,NaN,C50,8130.0,Malignant,2,0,0,2B,22.0,G2,71,L1201,NaN,NaN,NaN,NaN,NaN,NaN,Curative,NaN,NaN,NaN,NaN,R,3,NaN,NaN
1,10000752,F,810000752,A,A,2017-01-16,10335805,2015-11-11,C504,C50,8140.0,Malignant,NaN,0,NaN,NaN,22.0,G2,68,L0801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-09-18,L,1 - least deprived,NaN,NaN
2,10001050,F,810001050,A,A,2017-01-16,10335823,2015-10-24,NaN,C50,8130.0,Malignant,NaN,3,1,4C,22.0,G3,86,L0401,NaN,NaN,NaN,NaN,NaN,NaN,Non curative,NaN,NaN,NaN,2015-12-15,L,4,NaN,NaN
3,10001750,M,810001750,A,A,2017-01-16,10335873,2014-09-23,NaN,C50,8070.0,Malignant,NaN,NaN,NaN,NaN,NaN,G1,71,L0801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-09-23,L,1 - least deprived,NaN,NaN
4,10001824,F,810001824,S,A,2017-01-17,10335879,2015-03-15,NaN,C50,8070.0,Malignant,2b,NaN,0,3A,NaN,G2,87,L0801,NaN,NaN,NaN,NaN,NaN,NaN,Curative,1,NaN,NaN,2015-03-15,L,4,NaN,NaN

In [13]:
df.shape

(103192, 35)

In [14]:
df.isna().sum()

PATIENTID                       0
SEX                             0
LINKNUMBER                      0
ETHNICITY                    2572
NEWVITALSTATUS                  0
VITALSTATUSDATE                 0
TUMOURID                        0
DIAGNOSISDATEBEST               0
SITE_ICD10_O2                1555
SITE_ICD10_O2_3CHAR             0
MORPH_ICD10_O2                 38
BEHAVIOUR_ICD10_O2             53
T_BEST                       9259
N_BEST                      10588
M_BEST                      41861
STAGE_BEST                   9605
STAGE_BEST_SYSTEM           16986
GRADE                        6437
AGE                             0
CREG_CODE                       0
ER_STATUS                   24817
ER_SCORE                    61346
SCREENINGSTATUSFULL_CODE    33307
PR_STATUS                   54652
PR_SCORE                    78644
HER2_STATUS                 26491
CANCERCAREPLANINTENT        56877
PERFORMANCESTATUS           67044
CNS                         68789
ACE27                       98787
DATE_FIRST_SURGERY          16311
LATERALITY                   1471
QUINTILE_2015                   0
MERGED_PATIENT_ID           64603
LINK_NUMBER                 64603
dtype: int64

In [15]:
df.count()

PATIENTID                   103192
SEX                         103192
LINKNUMBER                  103192
ETHNICITY                   100620
NEWVITALSTATUS              103192
VITALSTATUSDATE             103192
TUMOURID                    103192
DIAGNOSISDATEBEST           103192
SITE_ICD10_O2               101637
SITE_ICD10_O2_3CHAR         103192
MORPH_ICD10_O2              103154
BEHAVIOUR_ICD10_O2          103139
T_BEST                       93933
N_BEST                       92604
M_BEST                       61331
STAGE_BEST                   93587
STAGE_BEST_SYSTEM            86206
GRADE                        96755
AGE                         103192
CREG_CODE                   103192
ER_STATUS                    78375
ER_SCORE                     41846
SCREENINGSTATUSFULL_CODE     69885
PR_STATUS                    48540
PR_SCORE                     24548
HER2_STATUS                  76701
CANCERCAREPLANINTENT         46315
PERFORMANCESTATUS            36148
CNS                          34403
ACE27                         4405
DATE_FIRST_SURGERY           86881
LATERALITY                  101721
QUINTILE_2015               103192
MERGED_PATIENT_ID            38589
LINK_NUMBER                  38589
dtype: int64

In [16]:
df.shape

(103192, 35)

In [17]:
df[df.groupby('PATIENTID')['PATIENTID'].transform('size') > 1].count()

PATIENTID                   0
SEX                         0
LINKNUMBER                  0
ETHNICITY                   0
NEWVITALSTATUS              0
VITALSTATUSDATE             0
TUMOURID                    0
DIAGNOSISDATEBEST           0
SITE_ICD10_O2               0
SITE_ICD10_O2_3CHAR         0
MORPH_ICD10_O2              0
BEHAVIOUR_ICD10_O2          0
T_BEST                      0
N_BEST                      0
M_BEST                      0
STAGE_BEST                  0
STAGE_BEST_SYSTEM           0
GRADE                       0
AGE                         0
CREG_CODE                   0
ER_STATUS                   0
ER_SCORE                    0
SCREENINGSTATUSFULL_CODE    0
PR_STATUS                   0
PR_SCORE                    0
HER2_STATUS                 0
CANCERCAREPLANINTENT        0
PERFORMANCESTATUS           0
CNS                         0
ACE27                       0
DATE_FIRST_SURGERY          0
LATERALITY                  0
QUINTILE_2015               0
MERGED_PATIENT_ID           0
LINK_NUMBER                 0
dtype: int64

In [18]:
df.to_csv('./Data/avpat_avtum_sactpat.csv', sep='^')