In [20]:
import pandas as pd
import numpy as np
from zipfile import ZipFile

In [21]:
pd.set_option('display.max_columns', None)

In [22]:
zf = ZipFile("../../Data/sim_sact_tumour.zip")
csv = zf.open("sim_sact_tumour.csv")
sim_sact_tumour = pd.read_csv(csv)
sim_sact_tumour.head()

,MERGED_TUMOUR_ID,MERGED_PATIENT_ID,CONSULTANT_SPECIALITY_CODE,PRIMARY_DIAGNOSIS,MORPHOLOGY_CLEAN
0,10000001,10000235,101.0,C61,81403.0
1,10000002,10000315,101.0,C679,81403.0
2,10000003,10000337,100.0,C500,NaN
3,10000004,10000480,303.0,C829,NaN
4,10000005,10000533,823.0,D473,NaN

In [23]:
sim_sact_tumour.shape

(299727, 5)

In [46]:
print("The original dataset has data for %d patients" % len(sim_sact_tumour))
print("After removing duplicates, the dataset has data for %d patients" % len(sim_sact_tumour.drop_duplicates()))
print("There are no duplicates in the dataset")

The original dataset has data for 124217 patients
After removing duplicates, the dataset has data for 124217 patients
There are no duplicates in the dataset

In [26]:
sim_sact_tumour[sim_sact_tumour.groupby('MERGED_PATIENT_ID')['MERGED_PATIENT_ID'].transform('size') > 1].count()

MERGED_TUMOUR_ID              175510
MERGED_PATIENT_ID             175510
CONSULTANT_SPECIALITY_CODE    175506
PRIMARY_DIAGNOSIS             175446
MORPHOLOGY_CLEAN               86818
dtype: int64

In [27]:
sim_sact_tumour[sim_sact_tumour.groupby('MERGED_PATIENT_ID')['MERGED_PATIENT_ID'].transform('size') == 1].count()

MERGED_TUMOUR_ID              124217
MERGED_PATIENT_ID             124217
CONSULTANT_SPECIALITY_CODE    124217
PRIMARY_DIAGNOSIS             124173
MORPHOLOGY_CLEAN               67420
dtype: int64

In [28]:
sim_sact_tumour = sim_sact_tumour[sim_sact_tumour.groupby('MERGED_PATIENT_ID')['MERGED_PATIENT_ID'].transform('size') == 1]
sim_sact_tumour.head()

,MERGED_TUMOUR_ID,MERGED_PATIENT_ID,CONSULTANT_SPECIALITY_CODE,PRIMARY_DIAGNOSIS,MORPHOLOGY_CLEAN
0,10000001,10000235,101.0,C61,81403.0
1,10000002,10000315,101.0,C679,81403.0
2,10000003,10000337,100.0,C500,NaN
3,10000004,10000480,303.0,C829,NaN
4,10000005,10000533,823.0,D473,NaN

In [29]:
sim_sact_tumour.shape

(124217, 5)

In [30]:
df = pd.read_csv("./Data/avpat_avtum_sactpat.csv", sep='^', index_col = 0)
df.head()

,PATIENTID,SEX,LINKNUMBER,ETHNICITY,NEWVITALSTATUS,VITALSTATUSDATE,TUMOURID,DIAGNOSISDATEBEST,SITE_ICD10_O2,SITE_ICD10_O2_3CHAR,MORPH_ICD10_O2,BEHAVIOUR_ICD10_O2,T_BEST,N_BEST,M_BEST,STAGE_BEST,STAGE_BEST_SYSTEM,GRADE,AGE,CREG_CODE,ER_STATUS,ER_SCORE,SCREENINGSTATUSFULL_CODE,PR_STATUS,PR_SCORE,HER2_STATUS,CANCERCAREPLANINTENT,PERFORMANCESTATUS,CNS,ACE27,DATE_FIRST_SURGERY,LATERALITY,QUINTILE_2015,MERGED_PATIENT_ID,LINK_NUMBER
0,10000724,M,810000724,A,A,2017-01-16,10335800,2013-09-08,NaN,C50,8130.0,Malignant,2,0,0,2B,22.0,G2,71,L1201,NaN,NaN,NaN,NaN,NaN,NaN,Curative,NaN,NaN,NaN,NaN,R,3,NaN,NaN
1,10000752,F,810000752,A,A,2017-01-16,10335805,2015-11-11,C504,C50,8140.0,Malignant,NaN,0,NaN,NaN,22.0,G2,68,L0801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-09-18,L,1 - least deprived,NaN,NaN
2,10001050,F,810001050,A,A,2017-01-16,10335823,2015-10-24,NaN,C50,8130.0,Malignant,NaN,3,1,4C,22.0,G3,86,L0401,NaN,NaN,NaN,NaN,NaN,NaN,Non curative,NaN,NaN,NaN,2015-12-15,L,4,NaN,NaN
3,10001750,M,810001750,A,A,2017-01-16,10335873,2014-09-23,NaN,C50,8070.0,Malignant,NaN,NaN,NaN,NaN,NaN,G1,71,L0801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-09-23,L,1 - least deprived,NaN,NaN
4,10001824,F,810001824,S,A,2017-01-17,10335879,2015-03-15,NaN,C50,8070.0,Malignant,2b,NaN,0,3A,NaN,G2,87,L0801,NaN,NaN,NaN,NaN,NaN,NaN,Curative,1,NaN,NaN,2015-03-15,L,4,NaN,NaN

In [31]:
df.shape

(103192, 35)

In [32]:
df = df.merge(sim_sact_tumour, left_on = 'MERGED_PATIENT_ID', right_on = 'MERGED_PATIENT_ID', how = 'left')

In [33]:
df.shape

(103192, 39)

In [34]:
df.head()

,PATIENTID,SEX,LINKNUMBER,ETHNICITY,NEWVITALSTATUS,VITALSTATUSDATE,TUMOURID,DIAGNOSISDATEBEST,SITE_ICD10_O2,SITE_ICD10_O2_3CHAR,MORPH_ICD10_O2,BEHAVIOUR_ICD10_O2,T_BEST,N_BEST,M_BEST,STAGE_BEST,STAGE_BEST_SYSTEM,GRADE,AGE,CREG_CODE,ER_STATUS,ER_SCORE,SCREENINGSTATUSFULL_CODE,PR_STATUS,PR_SCORE,HER2_STATUS,CANCERCAREPLANINTENT,PERFORMANCESTATUS,CNS,ACE27,DATE_FIRST_SURGERY,LATERALITY,QUINTILE_2015,MERGED_PATIENT_ID,LINK_NUMBER,MERGED_TUMOUR_ID,CONSULTANT_SPECIALITY_CODE,PRIMARY_DIAGNOSIS,MORPHOLOGY_CLEAN
0,10000724,M,810000724,A,A,2017-01-16,10335800,2013-09-08,NaN,C50,8130.0,Malignant,2,0,0,2B,22.0,G2,71,L1201,NaN,NaN,NaN,NaN,NaN,NaN,Curative,NaN,NaN,NaN,NaN,R,3,NaN,NaN,NaN,NaN,NaN,NaN
1,10000752,F,810000752,A,A,2017-01-16,10335805,2015-11-11,C504,C50,8140.0,Malignant,NaN,0,NaN,NaN,22.0,G2,68,L0801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-09-18,L,1 - least deprived,NaN,NaN,NaN,NaN,NaN,NaN
2,10001050,F,810001050,A,A,2017-01-16,10335823,2015-10-24,NaN,C50,8130.0,Malignant,NaN,3,1,4C,22.0,G3,86,L0401,NaN,NaN,NaN,NaN,NaN,NaN,Non curative,NaN,NaN,NaN,2015-12-15,L,4,NaN,NaN,NaN,NaN,NaN,NaN
3,10001750,M,810001750,A,A,2017-01-16,10335873,2014-09-23,NaN,C50,8070.0,Malignant,NaN,NaN,NaN,NaN,NaN,G1,71,L0801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-09-23,L,1 - least deprived,NaN,NaN,NaN,NaN,NaN,NaN
4,10001824,F,810001824,S,A,2017-01-17,10335879,2015-03-15,NaN,C50,8070.0,Malignant,2b,NaN,0,3A,NaN,G2,87,L0801,NaN,NaN,NaN,NaN,NaN,NaN,Curative,1,NaN,NaN,2015-03-15,L,4,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
df[df.groupby('PATIENTID')['PATIENTID'].transform('size') > 1].count()

PATIENTID                     0
SEX                           0
LINKNUMBER                    0
ETHNICITY                     0
NEWVITALSTATUS                0
VITALSTATUSDATE               0
TUMOURID                      0
DIAGNOSISDATEBEST             0
SITE_ICD10_O2                 0
SITE_ICD10_O2_3CHAR           0
MORPH_ICD10_O2                0
BEHAVIOUR_ICD10_O2            0
T_BEST                        0
N_BEST                        0
M_BEST                        0
STAGE_BEST                    0
STAGE_BEST_SYSTEM             0
GRADE                         0
AGE                           0
CREG_CODE                     0
ER_STATUS                     0
ER_SCORE                      0
SCREENINGSTATUSFULL_CODE      0
PR_STATUS                     0
PR_SCORE                      0
HER2_STATUS                   0
CANCERCAREPLANINTENT          0
PERFORMANCESTATUS             0
CNS                           0
ACE27                         0
DATE_FIRST_SURGERY            0
LATERALITY                    0
QUINTILE_2015                 0
MERGED_PATIENT_ID             0
LINK_NUMBER                   0
MERGED_TUMOUR_ID              0
CONSULTANT_SPECIALITY_CODE    0
PRIMARY_DIAGNOSIS             0
MORPHOLOGY_CLEAN              0
dtype: int64

In [37]:
df.isna().sum()

PATIENTID                         0
SEX                               0
LINKNUMBER                        0
ETHNICITY                      2572
NEWVITALSTATUS                    0
VITALSTATUSDATE                   0
TUMOURID                          0
DIAGNOSISDATEBEST                 0
SITE_ICD10_O2                  1555
SITE_ICD10_O2_3CHAR               0
MORPH_ICD10_O2                   38
BEHAVIOUR_ICD10_O2               53
T_BEST                         9259
N_BEST                        10588
M_BEST                        41861
STAGE_BEST                     9605
STAGE_BEST_SYSTEM             16986
GRADE                          6437
AGE                               0
CREG_CODE                         0
ER_STATUS                     24817
ER_SCORE                      61346
SCREENINGSTATUSFULL_CODE      33307
PR_STATUS                     54652
PR_SCORE                      78644
HER2_STATUS                   26491
CANCERCAREPLANINTENT          56877
PERFORMANCESTATUS             67044
CNS                           68789
ACE27                         98787
DATE_FIRST_SURGERY            16311
LATERALITY                     1471
QUINTILE_2015                     0
MERGED_PATIENT_ID             64603
LINK_NUMBER                   64603
MERGED_TUMOUR_ID              86121
CONSULTANT_SPECIALITY_CODE    86121
PRIMARY_DIAGNOSIS             86124
MORPHOLOGY_CLEAN              92897
dtype: int64

In [38]:
df.count()

PATIENTID                     103192
SEX                           103192
LINKNUMBER                    103192
ETHNICITY                     100620
NEWVITALSTATUS                103192
VITALSTATUSDATE               103192
TUMOURID                      103192
DIAGNOSISDATEBEST             103192
SITE_ICD10_O2                 101637
SITE_ICD10_O2_3CHAR           103192
MORPH_ICD10_O2                103154
BEHAVIOUR_ICD10_O2            103139
T_BEST                         93933
N_BEST                         92604
M_BEST                         61331
STAGE_BEST                     93587
STAGE_BEST_SYSTEM              86206
GRADE                          96755
AGE                           103192
CREG_CODE                     103192
ER_STATUS                      78375
ER_SCORE                       41846
SCREENINGSTATUSFULL_CODE       69885
PR_STATUS                      48540
PR_SCORE                       24548
HER2_STATUS                    76701
CANCERCAREPLANINTENT           46315
PERFORMANCESTATUS              36148
CNS                            34403
ACE27                           4405
DATE_FIRST_SURGERY             86881
LATERALITY                    101721
QUINTILE_2015                 103192
MERGED_PATIENT_ID              38589
LINK_NUMBER                    38589
MERGED_TUMOUR_ID               17071
CONSULTANT_SPECIALITY_CODE     17071
PRIMARY_DIAGNOSIS              17068
MORPHOLOGY_CLEAN               10295
dtype: int64

In [40]:
pd.set_option('display.max_columns', None) 
pd.set_option('display.max_rows', None)

In [41]:
df['PRIMARY_DIAGNOSIS'].value_counts()

C509    11627
C504     2255
C502      581
C501      572
C505      418
C503      399
C508      274
C833      101
C500       87
D059       52
C506       47
D051       43
C80        41
C56        32
C795       25
C20        23
C349       22
C900       19
C773       17
C187       15
C182       15
C837       13
C189       12
C831       11
C155       11
C829       10
D057       10
C859       10
C851       10
C539       10
C839        9
C61         8
C439        8
C679        7
C259        7
C830        7
C910        7
C911        6
C160        6
C341        6
C169        6
C64         6
C880        5
C343        5
C97         5
C19         5
C185        5
C857        5
C541        5
C819        5
C159        4
C799        4
C154        4
D489        4
C798        4
C920        4
C696        3
D471        3
D414        3
D45         3
C921        3
C210        3
C109        3
C499        3
c509        3
D486        3
C180        3
C435        3
C787        3
D050        3
Z458        3
C23         3
C73         3
C179        3
C90         2
C835        2
C812        2
C184        2
C186        2
C459        2
C838        2
C437        2
C719        2
C767        2
C629        2
C793        2
D473        2
C163        2
C770        2
C811        2
C250        2
C171        2
C342        2
C946        2
C824        2
C162        2
C844        1
D469        1
C441        1
C914        1
C227        1
C915        1
C490        1
C947        1
C768        1
C158        1
I89         1
C929        1
C211        1
C762        1
A419        1
C443        1
C029        1
C916        1
C348        1
C570        1
C449        1
C433        1
C710        1
C491        1
C161        1
C884        1
C847        1
C269        1
C780        1
C049        1
C712        1
K565        1
C183        1
C090        1
C444        1
C822        1
D24         1
C917        1
C218        1
D479        1
C772        1
C796        1
C181        1
C783        1
C820        1
C340        1
C240        1
C21         1
C301        1
D330        1
B370        1
C549        1
C492        1
D470        1
C252        1
C55         1
C450        1
C779        1
C672        1
C574        1
C577        1
Name: PRIMARY_DIAGNOSIS, dtype: int64

In [42]:
df['PRIMARY_DIAGNOSIS'].nunique()

157

In [43]:
df.head()

,PATIENTID,SEX,LINKNUMBER,ETHNICITY,NEWVITALSTATUS,VITALSTATUSDATE,TUMOURID,DIAGNOSISDATEBEST,SITE_ICD10_O2,SITE_ICD10_O2_3CHAR,MORPH_ICD10_O2,BEHAVIOUR_ICD10_O2,T_BEST,N_BEST,M_BEST,STAGE_BEST,STAGE_BEST_SYSTEM,GRADE,AGE,CREG_CODE,ER_STATUS,ER_SCORE,SCREENINGSTATUSFULL_CODE,PR_STATUS,PR_SCORE,HER2_STATUS,CANCERCAREPLANINTENT,PERFORMANCESTATUS,CNS,ACE27,DATE_FIRST_SURGERY,LATERALITY,QUINTILE_2015,MERGED_PATIENT_ID,LINK_NUMBER,MERGED_TUMOUR_ID,CONSULTANT_SPECIALITY_CODE,PRIMARY_DIAGNOSIS,MORPHOLOGY_CLEAN
0,10000724,M,810000724,A,A,2017-01-16,10335800,2013-09-08,NaN,C50,8130.0,Malignant,2,0,0,2B,22.0,G2,71,L1201,NaN,NaN,NaN,NaN,NaN,NaN,Curative,NaN,NaN,NaN,NaN,R,3,NaN,NaN,NaN,NaN,NaN,NaN
1,10000752,F,810000752,A,A,2017-01-16,10335805,2015-11-11,C504,C50,8140.0,Malignant,NaN,0,NaN,NaN,22.0,G2,68,L0801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016-09-18,L,1 - least deprived,NaN,NaN,NaN,NaN,NaN,NaN
2,10001050,F,810001050,A,A,2017-01-16,10335823,2015-10-24,NaN,C50,8130.0,Malignant,NaN,3,1,4C,22.0,G3,86,L0401,NaN,NaN,NaN,NaN,NaN,NaN,Non curative,NaN,NaN,NaN,2015-12-15,L,4,NaN,NaN,NaN,NaN,NaN,NaN
3,10001750,M,810001750,A,A,2017-01-16,10335873,2014-09-23,NaN,C50,8070.0,Malignant,NaN,NaN,NaN,NaN,NaN,G1,71,L0801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014-09-23,L,1 - least deprived,NaN,NaN,NaN,NaN,NaN,NaN
4,10001824,F,810001824,S,A,2017-01-17,10335879,2015-03-15,NaN,C50,8070.0,Malignant,2b,NaN,0,3A,NaN,G2,87,L0801,NaN,NaN,NaN,NaN,NaN,NaN,Curative,1,NaN,NaN,2015-03-15,L,4,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
df.shape

(103192, 39)

In [45]:
df.to_csv('./Data/avpat_avtum_sactpat_sacttum.csv', sep='^')